# BUILD
# use latest version of node
FROM node:12.4.0-alpine AS builder

# set working directory
COPY ./src ./src
COPY .babelrc ./
COPY package*.json ./

# install
RUN npm install
RUN npm run build:master


# SERVICE
# use latest version of node
FROM node:12.4.0-alpine
RUN apk add --no-cache bash
RUN apk add --no-cache curl

# set working directory
WORKDIR /master
COPY --from=builder ./dist/master ./dist/master
COPY package*.json ./
COPY .env ./

# install
RUN npm install pm2 -g
RUN npm install --only=prod

CMD [ "pm2-runtime", "start", "--name", "master", "npm", "--", "run", "server:master" ]